<?php
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\lesroidelareno\lesroidelareno;

/**
 *
 * @file
 * Primary module hooks for Creation site virtuel module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Ajouter la traduction sur les champs name de site_internet_entity et
 * site_type_datas.
 * implement hook_update_8001
 *
 * @see https://www.drupal.org/node/2554097
 */
function ___creation_site_virtuel_update_8001() {
  /**
   *
   * @var \Drupal\Core\Entity\EntityDefinitionUpdateManagerInterface $updateManager
   */
  $updateManager = \Drupal::entityDefinitionUpdateManager();
  /**
   *
   * @var \Drupal\Core\Field\BaseFieldDefinition $nameModelCv
   */
  $nameSiteInternetEntity = $updateManager->getFieldStorageDefinition('name', 'site_internet_entity');
  $nameSiteInternetEntity->setTranslatable(true);
  $nameSiteInternetEntity->setSetting('max_length', 250);
  $updateManager->updateFieldStorageDefinition($nameSiteInternetEntity);
  /**
   *
   * @var \Drupal\Core\Field\BaseFieldDefinition $nameModelCv
   */
  $nameSiteTypeDatas = $updateManager->getFieldStorageDefinition('name', 'site_type_datas');
  $nameSiteTypeDatas->setTranslatable(true);
  $nameSiteTypeDatas->setSetting('max_length', 250);
  $updateManager->updateFieldStorageDefinition($nameSiteTypeDatas);
}

/**
 * Update value max_length from 50 to 250.
 *
 * implement hook_update_8001
 *
 * @see https://www.drupal.org/node/2554097
 */
function __creation_site_virtuel_update_name_max_length($entity_type_id) {
  // Retrieve existing field data.
  $database = \Drupal::database();
  $names = $database->select($entity_type_id . '_field_data', 'et')->fields('et', [
    'id',
    'langcode',
    'name'
  ])->execute()->fetchAll(\PDO::FETCH_ASSOC);
  // Remove data from the column.
  $database->update($entity_type_id . '_field_data')->fields([
    'name' => NULL
  ])->execute();
  // Remove old definition field.
  $updateManager = \Drupal::entityDefinitionUpdateManager();
  $storagedef = $updateManager->getFieldStorageDefinition('name', $entity_type_id);
  $updateManager->uninstallFieldStorageDefinition($storagedef);
  // Load new definition field in code.
  /**
   *
   * @var \Drupal\Core\Entity\EntityFieldManager $fieldManager
   */
  $fieldManager = \Drupal::service('entity_field.manager');
  $fields = $fieldManager->getFieldStorageDefinitions($entity_type_id);
  $updateManager->installFieldStorageDefinition('name', $entity_type_id, "creation_site_virtuel", $fields['name']);
  // Restore entity data in the new schema.
  foreach ($names as $name) {
    $database->update($entity_type_id . '_field_data')->fields([
      'name' => $name['name']
    ])->condition('id', $name['id'])->condition('langcode', $name['langcode'])->execute();
  }
}

/**
 * Update value max_length from 50 to 250.
 *
 * implement hook_update_8001
 *
 * @see https://www.drupal.org/node/2554097
 */
function creation_site_virtuel_update_8001() {
  __creation_site_virtuel_update_name_max_length('site_type_datas');
  __creation_site_virtuel_update_name_max_length('site_internet_entity');
}

/**
 * implement hook_entity_base_field_info
 *
 * @param EntityTypeInterface $entity_type
 */
function creation_site_virtuel_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'site_internet_entity') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'paragraph') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'block_content') {
    $fields['layout_paragraphs'] = BaseFieldDefinition::create('entity_reference')->setLabel(t(' Sections (@Depreciate) '))->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)->setDisplayOptions('form', [
      'type' => 'creationsitevirtuelcomplexinline',
      'weight' => 0
    ])->setDisplayConfigurable('form', TRUE)->setDisplayConfigurable('view', TRUE)->setSetting('target_type', 'paragraph')->setSetting('handler', 'default')->setTranslatable(true)->setSetting('allow_duplicate', true);
    $fields['user_id'] = BaseFieldDefinition::create('entity_reference')->setLabel(t(' User Name '))->setRequired(TRUE)->setDescription(t('The Name of the associated user.'))->setSetting('target_type', 'user')->setSetting('handler', 'default')->setDisplayOptions('view', array(
      'label' => 'above',
      'type' => 'entity_reference_label',
      'weight' => -3
    ))->setDisplayOptions('form', [
      'type' => 'entity_reference_autocomplete',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'size' => 60,
        'autocomplete_type' => 'tags',
        'placeholder' => ''
      ),
      'weight' => -3
    ])->setDisplayConfigurable('form', TRUE)->setDisplayConfigurable('view', TRUE)->setDefaultValueCallback('\Drupal\creation_site_virtuel\CreationSiteVirtuel::getCurrentUser');
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_product') {
    $fields['layout_paragraphs'] = BaseFieldDefinition::create('entity_reference')->setLabel(t(' Sections (@Depreciate) '))->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)->setDisplayOptions('form', [
      'type' => 'creationsitevirtuelcomplexinline',
      'weight' => 39
    ])->setDisplayConfigurable('form', TRUE)->setDisplayConfigurable('view', TRUE)->setSetting('target_type', 'paragraph')->setSetting('handler', 'default')->setTranslatable(true)->setSetting('allow_duplicate', true);
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_payment') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_payment_method') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_order') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_order_item') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_promotion') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_promotion_coupon') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_shipping_method') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_shipment') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_stock_location') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'commerce_store') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'blocks_contents') {
    __creation_site_virtuel_fields_domain($fields);
  }
  elseif ($entity_type->id() == 'bks_autoecole_heures') {
    __creation_site_virtuel_fields_domain($fields);
  }
  //
  elseif ($entity_type->id() == 'booking_reservation') {
    __creation_site_virtuel_fields_domain($fields);
  }
  // elseif ($entity_type->id() == 'dis_period_entity') {
  // __creation_site_virtuel_fields_domain($fields);
  // }
  // elseif ($entity_type->id() == 'equipes_entity') {
  // __creation_site_virtuel_fields_domain($fields);
  // }
  // elseif ($entity_type->id() == 'submit_rdv_entity') {
  // __creation_site_virtuel_fields_domain($fields);
  // }
  return $fields;
}

/**
 *
 * @param array $fields
 */
function __creation_site_virtuel_fields_domain(array &$fields) {
  if (\Drupal::moduleHandler()->moduleExists('domain')) {
    $field_access = \Drupal\domain_access\DomainAccessManagerInterface::DOMAIN_ACCESS_FIELD;
    $field_source = \Drupal\domain_source\DomainSourceElementManagerInterface::DOMAIN_SOURCE_FIELD;
    //
    $fields[$field_access] = BaseFieldDefinition::create('entity_reference')->setLabel(t(" Domain access "))->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)->setTranslatable(false)->setDisplayOptions('form', [
      'type' => 'select2_entity_reference',
      'weight' => 40,
      'settings' => [
        'autocomplete' => true
      ]
    ])->setSetting('handler', 'default')->setSetting('target_type', 'domain')->setDisplayConfigurable('form', TRUE)->setDisplayConfigurable('view', TRUE)->setDefaultValueCallback('\Drupal\creation_site_virtuel\CreationSiteVirtuel::getActiveDomain');
    //
    $fields[$field_source] = BaseFieldDefinition::create('entity_reference')->setLabel(t(" Domain source "))->setDisplayOptions('form', [
      'type' => 'options_select',
      'weight' => 40
    ])->setSetting('handler', 'default')->setSetting('target_type', 'domain')->setDisplayConfigurable('form', TRUE)->setDisplayConfigurable('view', TRUE)->setTranslatable(false);
  }
}

/**
 * Implements hook_theme().
 */
function creation_site_virtuel_theme() {
  $theme = [];
  $theme['site_internet_entity'] = [
    'render element' => 'elements',
    'file' => 'site_internet_entity.page.inc',
    'template' => 'site_internet_entity'
  ];
  $theme['site_internet_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => [
      'content' => NULL
    ],
    'file' => 'site_internet_entity.page.inc'
  ];
  $theme['site_internet_entity_edit_form'] = [
    'render element' => 'form'
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function creation_site_virtuel_theme_suggestions_site_internet_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#site_internet_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  
  $suggestions[] = 'site_internet_entity__' . $sanitized_view_mode;
  $suggestions[] = 'site_internet_entity__' . $entity->bundle();
  $suggestions[] = 'site_internet_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'site_internet_entity__' . $entity->id();
  $suggestions[] = 'site_internet_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * implement hook_field_widget_WIDGET_TYPE_form_alter
 * on affiche un message si le widget est inline_entity_form_complex pour les
 * paragraphes.
 */
function creation_site_virtuel_field_widget_inline_entity_form_complex_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  if (!empty($element['entities']['#entity_type']) && $element['entities']['#entity_type'] == 'paragraph') {
  /**
   * On masque pour l'instant, car on doit publier la version 1.
   */
    // \Drupal::messenger()->addError(' Le widget "Inline entity form - Complex"
    // n\'est pas compatible avec paragraph, utiliser le widget "Create site
    // virtual Complexe inline". Champs : ' . $element['#ief_id']);
  }
}

function creation_site_virtuel_field_widget_creationsitevirtuelcomplexinline_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  /**
   *
   * @var \Drupal\Core\Field\FieldItemListInterface $items
   */
  $items = $context['items'];
  
  // On n'essaie de faire des copie de contenus.
  if ($items->getEntity()->isNew()) {
    /**
     *
     * @var \Drupal\creation_site_virtuel\Plugin\Field\FieldWidget\CreationSiteVirtuelComplexInline $widget
     */
    $widget = $context['widget'];
    $ief_id = $widget->_getIefId();
    $entities = $form_state->get([
      'inline_entity_form',
      $ief_id,
      'entities'
    ]);
    if ($form_state->getTriggeringElement()) {
      // \Stephane888\Debug\debugLog::$max_depth = 4;
      // \Stephane888\Debug\debugLog::kintDebugDrupal($element,
      // 'getTriggeringElement', true);
      $element['#access'] = false;
      $element = [
        [
          '#theme' => 'status_messages',
          '#message_list' => [
            "warning" => [
              'Cliquez sur sur le bouton ci-dessous ( " Creation de ... " ) afin de generer votre contenu.',
              'Cela peut prendre quelques minutes en fonction de la taille des contenus à generer '
            ]
          ]
        ],
        $element
      ];
    }
    // uniquement lors de la creation d'un contenu, on duplique les contenus
    // definies par defaut.
    elseif (!$form_state->get('default_value_widget') && !$form_state->getTriggeringElement()) {
      
      if (!empty($entities)) {
        $field_access = \Drupal\domain_access\DomainAccessManagerInterface::DOMAIN_ACCESS_FIELD;
        $field_source = \Drupal\domain_source\DomainSourceElementManagerInterface::DOMAIN_SOURCE_FIELD;
        $setFields = [
          $field_access => lesroidelareno::getCurrentDomainId(),
          $field_source => lesroidelareno::getCurrentDomainId()
        ];
        $uid = \Drupal::currentUser()->id();
        $subDatas = [];
        /**
         *
         * @var \Drupal\apivuejs\Services\DuplicateEntityReference $duplicate_reference
         */
        $duplicate_reference = \Drupal::service('apivuejs.duplicate_reference');
        // On met à jour les données present dans $form_state.
        foreach ($entities as $k => $entity) {
          /**
           *
           * @var \Drupal\commerce_product\Entity\Product $cloneNode
           */
          $cloneNode = $entity['entity']->createDuplicate();
          // On verifie si l'entité a le champs domain acces,
          if ($cloneNode->hasField($field_access)) {
            $cloneNode->set($field_access, lesroidelareno::getCurrentDomainId());
          }
          if ($cloneNode->hasField($field_source)) {
            $cloneNode->set($field_source, lesroidelareno::getCurrentDomainId());
          }
          // Les variations de produits ne sont pas duppliquer
          if ($cloneNode->getEntityTypeId() == 'commerce_product') {
            $duplicate_reference->duplicateProduct($entity['entity'], $cloneNode, true, $uid, $subDatas);
          }
          else {
            $cloneNode = $duplicate_reference->duplicateEntity($cloneNode, false, [], $setFields);
          }
          $entities[$k]['needs_save'] = true;
          $entities[$k]['form'] = null;
          $entities[$k]['entity'] = $cloneNode;
        }
        //
        $form_state->set([
          'inline_entity_form',
          $ief_id,
          'entities'
        ], $entities);
        // On met à jour les données present dans le bloc d'affichage.
        foreach ($element['entities'] as $k => $entity) {
          if (!empty($entity['#entity'])) {
            /**
             *
             * @var \Drupal\node\Entity\Node $node
             */
            $node = $element['entities'][$k]['#entity'];
            $cloneNodeDisplay = $node->createDuplicate();
            if ($cloneNodeDisplay->hasField($field_access)) {
              $cloneNodeDisplay->set($field_access, lesroidelareno::getCurrentDomainId());
            }
            if ($cloneNodeDisplay->hasField($field_source)) {
              $cloneNodeDisplay->set($field_source, lesroidelareno::getCurrentDomainId());
            }
            $element['entities'][$k]['#entity'] = $cloneNodeDisplay;
            $element['entities'][$k]['#needs_save'] = true;
          }
        }
      }
      else {
        $message = "Aucun contenu par defaut pour le champs : " . $items->getName();
        \Drupal::messenger()->addStatus($message);
      }
    }
    // $form_values = NestedArray::getValue($form_state->getValues(),
    // $reference_form['#parents']);
  }
  else {
    // $widget = $context['widget'];
    // $ief_id = $widget->_getIefId();
    // $entities = $form_state->get([
    // 'inline_entity_form',
    // $ief_id,
    // 'entities'
    // ]);
    
    // foreach ($entities as $vals) {
    // foreach ($vals as $entity) {
    // /**
    // *
    // * @var \Drupal\block_content\Entity\BlockContent $entity
    // */
    // if ($entity instanceof Drupal\block_content\Entity\BlockContent &&
    // $entity->getEntityTypeId() == 'block_content') {
    
    // }
    // }
    // }
  }
}


