creation_site_virtuel.site_internet_entity_type.*:
  type: config_entity
  label: 'Site internet entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    site_type_datas:
      type: interger
      label: 'id du contenu'

